### ISSUE TITLE
Addon Version depends on OS/Hardware/Distributor - more options

### ISSUE THREAD

**Issue by ManOki** [robwebset/service.addonsync#1]
Hi,

I have several Kodi installations on different Hardware and OS. In my case, AddonSync don't sync i.e. my pvr settings between a Windows 10 and an RaspberryPi3.

So the current bundled version of pvr.hts in Windows is 2.2.15. At Raspian, I am using the repository from pplware ([Kodi Wiki](http://kodi.wiki/view/HOW-TO:Install_Kodi_on_Raspberry_Pi), [Repo](http://pipplware.pplware.pt/pipplware/dists/jessie/main/binary)) with version 2.2.12.

As I can see from the changelog, there are no big differences than some bug fixes. The configuration files are equal and therefore could be synced.

I don't know an elegant solution, but two ideas might be regex/startsWith for the version parameter in the hashdata.xml or an option to completly ignore that and leave emerging problems to the user.

Thanks for your help and for the great addon
ManOki

**Comment by robwebset** [comment]
I have added an option in the AddonSync setting to toggle if the version numbere should be checked before performing the resync.

Hopefully this will mean that you can get your addons to sync OK. (You should be able to undet the value)

Available in AddonSync 100.1.0 (In the latest robwebset repository)
